apiVersion: v1
kind: Pod
metadata:
  name: host-path-volume
spec:
  containers:
  - image: nginx
    name: test-container
    ports:
      - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html/test.html
      subPath: test.html
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /data
      # this field is optional
      type: Directory