apiVersion: v1
kind: Pod
metadata: 
  name: pod-nginx
  labels:
    app: my-app
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: redis
      image: redis:latest
      ports:
        - containerPort: 6379