apiVersion: v1
kind: Pod
metadata: 
  name: cpu-demo
  namespace: ns-production
spec:
  containers:
    - name: cpu-demo
      image: nginx:latest
      resources:
        requests:
          cpu: "0.6"
          memory: "256M"
      args:
        # - -cpus: "2",
        # - "2"