apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 2
  selector:
    app: my-label
  template:
    metadata:
      name: my-label
      labels:
        app: my-label
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
