apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
  labels:
    app: kibana
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 5601 
      nodePort: 31230
  selector:
    app: kibana
  