apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  namespace: devops-tools
spec:
  selector: 
    app: landing-page
  type: NodePort  
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31999