apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-demo
  labels:
    name: pv
spec:
  storageClassName: mystorageclass
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/pv-demo"