apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: frontend
  minReplicas: 4
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50